### ISSUE TITLE
Git branch value is  not correct for CI Jenkins build scans

### ISSUE THREAD

**Issue by sfc-gh-akazantsev** [gradle/common-custom-user-data-maven-extension#14]
Hi team,
We've noticed that all our CI builds have wrong 'git branch' tag.
it is always represents jenkins job value which for PRs is 'PR-12345' form.

this is due to the below code

> private String getGitBranchName(Supplier<String> gitCommand) {
>             if (isJenkins() || isHudson()) {
>                 Optional<String> branch = Utils.envVariable("BRANCH_NAME");
>                 if (branch.isPresent()) {
>                     return branch.get();
>                 }
>             }
>             return gitCommand.get();
>         }
> 
> 

BRANCH_NAME in our jenkins never matches git branch. its more like jenkins job branch.

there is GIT_BRANCH var for git based projects 

https://wiki.jenkins.io/display/JENKINS/Building+a+software+project

**Comment by runningcode** [comment]
Hi @sfc-gh-akazantsev , based on our discussion in slack, `BRANCH_NAME` seems to be the best variable for the majority of use cases of this maven extension. Is that correct?

**Comment by sfc-gh-akazantsev** [comment]
to record some findings:
this seems to be related how GH is configured to do PRs as it creates extra branches for PRs separate from feature branch.

they're all under the refs/pull/ namespace, https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by runningcode** [comment]
Closing this out for now. Since we determined this behavior is best.
