### ISSUE TITLE
Improve how customized version of the extension should be made

### ISSUE THREAD

**Issue by yeikel** [gradle/common-custom-user-data-maven-extension#210]
Currently, the recommended method to extend this project is to [create a copy of this repository and extend it. ](https://github.com/gradle/common-custom-user-data-maven-extension?tab=readme-ov-file#developing-a-customized-version-of-the-extension)

Having my own copy/fork introduces various challenges, in particular how to keep it up to date with the various changes such as https://github.com/gradle/common-custom-user-data-maven-extension/pull/209 

I would like to consume this project as a JAR, and overwrite/update what does not work for me via Java overwrite constructs. Many of the current methods are private/static and do not allow this level of control without the copy you suggested

**Comment by clayburn** [comment]
@yeikel - thanks for the feedback. We have no plans at the moment to make this JAR open for extension. Our recommendation remains to create a fork of the repository, keep only the parts that you need, and add any customization that makes sense for your project(s).

If you are a Develocity customer, please reach out to the team that you work with and we would be happy to assist you with this and discuss this further.
